version: "3"

services:

  database:
    image: postgres:latest
    volumes:
      - ./data_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: symbiot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  server:
    build:
      context:
        ./symbiot_server
    ports:
      - "5000:5000"
    depends_on:
      - database
    expose:
      - 5000

  core:
    build:
      context:
       ./symbiot_core
    ports:
      - "5001:5001"